package pojos;
// Generated Feb 19, 2021 3:41:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Integer id;
     private String bookId;
     private String title;
     private String author;
     private String bookCategory;
     private String publishingHouse;
     private Date publishingDate;
     private int pages;
     private boolean available;

    public Book() {
    }

    public Book(String bookId, String title, String author, String bookCategory, String publishingHouse, Date publishingDate, int pages, boolean available) {
       this.bookId = bookId;
       this.title = title;
       this.author = author;
       this.bookCategory = bookCategory;
       this.publishingHouse = publishingHouse;
       this.publishingDate = publishingDate;
       this.pages = pages;
       this.available = available;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getBookId() {
        return this.bookId;
    }
    
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getBookCategory() {
        return this.bookCategory;
    }
    
    public void setBookCategory(String bookCategory) {
        this.bookCategory = bookCategory;
    }
    public String getPublishingHouse() {
        return this.publishingHouse;
    }
    
    public void setPublishingHouse(String publishingHouse) {
        this.publishingHouse = publishingHouse;
    }
    public Date getPublishingDate() {
        return this.publishingDate;
    }
    
    public void setPublishingDate(Date publishingDate) {
        this.publishingDate = publishingDate;
    }
    public int getPages() {
        return this.pages;
    }
    
    public void setPages(int pages) {
        this.pages = pages;
    }
    public boolean isAvailable() {
        return this.available;
    }
    
    public void setAvailable(boolean available) {
        this.available = available;
    }




}


