package pojos;
// Generated Feb 19, 2021 3:41:42 PM by Hibernate Tools 4.3.1



/**
 * Bookcategory generated by hbm2java
 */
public class Bookcategory  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String name;

    public Bookcategory() {
    }

    public Bookcategory(String code, String name) {
       this.code = code;
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


