package pojos;
// Generated Feb 19, 2021 3:41:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Booktransaction generated by hbm2java
 */
public class Booktransaction  implements java.io.Serializable {


     private Integer id;
     private String clientName;
     private String bookTitle;
     private String transactionType;
     private Date transactionDate;
     private Date returnDate;

    public Booktransaction() {
    }

    public Booktransaction(String clientName, String bookTitle, String transactionType, Date transactionDate, Date returnDate) {
       this.clientName = clientName;
       this.bookTitle = bookTitle;
       this.transactionType = transactionType;
       this.transactionDate = transactionDate;
       this.returnDate = returnDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }
    public String getBookTitle() {
        return this.bookTitle;
    }
    
    public void setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle;
    }
    public String getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

//    public String getTransactionType(String CategoryCheckIn) {
//        return this.transactionType; 
//    }
//
//    public Date getTransactionDate(Date TransactionDate) {
//        return this.transactionDate;
//    }
//
//    public Date getReturnDate(Date ReturnDate) {
//       return this.returnDate;
//    }




}


