package pojos;
// Generated Feb 19, 2021 3:41:42 PM by Hibernate Tools 4.3.1

import java.io.FileInputStream;




/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer id;
     private String regId;
     private String firstName;
     private String lastName;
     private String phoneNumber;
     private String email;
     private byte[] photo;
     private String clientCategory;

    public Client() {
    }

	
    public Client(String regId, String firstName, String lastName, String phoneNumber, String email, String clientCategory) {
        this.regId = regId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.clientCategory = clientCategory;
    }
    public Client(String regId, String firstName, String lastName, String phoneNumber, String email, byte[] photo, String clientCategory) {
       this.regId = regId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.phoneNumber = phoneNumber;
       this.email = email;
       this.photo = photo;
       this.clientCategory = clientCategory;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRegId() {
        return this.regId;
    }
    
    public void setRegId(String regId) {
        this.regId = regId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public String getClientCategory() {
        return this.clientCategory;
    }
    
    public void setClientCategory(String clientCategory) {
        this.clientCategory = clientCategory;
    }

    public void setPhoto(FileInputStream fis) {
       this.photo = photo;
    }




}


